### ISSUE TITLE
README wrong?

### ISSUE THREAD

**Issue by turian** [pranaymanocha/PerceptualAudio#12]
The readme says that you should get 
distance = 0.1928.

with
```
cd metric_code
python metric_use_simple.py --e0 ../sample_audio/ref.wav --e1 ../sample_audio/2.wav
```

However,

1) I see slightly different numbers each run on GPU. Why is it not deterministic?

0.19287356734275818
0.19287368655204773
0.19287356734275818

2) This is actually 0.1929, regardless of the nondeterminism.

3) If I run on a CPU, I get the same numbers every time:

0.19290807843208313

You can try here:

https://colab.research.google.com/drive/1yewloMpVxNXAKRxzsx_mZEj23hNkkkap?usp=sharing

You can switch the runtime type between GPU and CPU

**Comment by richzhang** [comment]
I think (certain) GPUs are not deterministic, so it's not specific to this library: https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9911-determinism-in-deep-learning.pdf

**Comment by pranaymanocha** [comment]
Hi. Thanks for your comments.
1) It's (somewhat) common to have an lsb difference in results for varying GPU's.
2) You are right. Even on my machine (whose specs I wrote down earlier), I rounded off the decimal wrongly. It should be **0.1929** as you said.
Thanks for noticing this. I'll also update the repo about the slight variation due to machines.

**Comment by turian** [comment]
@richzhang would this apply even on one GPU just loading and re-running the model several times, like in my colab? If so doesn't that mean the gradient will oscillate around the target for example?

**Comment by richzhang** [comment]
I'm not an expert on the non-determinism, but I don't think any non-determinism you observe is originating from this codebase (as evidenced by the CPU being deterministic). I think there may be some flags you can turn on in cudnn to make it slower but deterministic.

**Comment by turian** [comment]
@richzhang and @pranaymanocha thank you for the explanations.
