### ISSUE TITLE
Issues with pip version

### ISSUE THREAD

**Issue by vinayak19th** [pranaymanocha/PerceptualAudio#13]
Currently having many issues in using the pip version. There seems to be an error in reagards to the module "helper" as well as the fact that the activation function was set to "lrelu" rather than "relu" or 'LeakyRelu". Can you please look into that

**Comment by pranaymanocha** [comment]
Hi. Thanks for pointing it out. Somehow I had not uploaded the pretrained model and it was causing things to crash. I have fixed that, along with a few fixes. Please let me know if you face any more problems. Sorry for the trouble!

**Comment by vinayak19th** [comment]
Thank you. No issues, great work though

**Comment by vinayak19th** [comment]
Traceback (most recent call last):
     File "<string>", line 1, in <module>
     File "/tmp/pip-install-sd1aqaln/dpam/setup.py", line 10, in <module>
        directories = os.listdir('/n/fs/percepaudio/PerceptualAudio/dpam/pre-model/')
    FileNotFoundError: [Errno 2] No such file or directory: '/n/fs/percepaudio/PerceptualAudio/dpam/pre-model/'
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-sd1aqaln/dpam/
    ----------------------------------------

There are still issues with the pip version. CDPAM is also missing a README_PYPI

**Comment by pranaymanocha** [comment]
Updated both DPAM and CDPAM. Sorry for that. Didnt realise that I didnt update the path locations for the pretrained models.

**Comment by pranaymanocha** [comment]
I'll close this for now, but feel free to open it if you find more bugs. Thanks!
