### ISSUE TITLE
Allow user to specify device for CDPAM

### ISSUE THREAD

**Issue by iver56** [pranaymanocha/PerceptualAudio#23]
First, thanks for sharing CDPAM with the world! :) I've read good things about it in your paper.

Although CUDA is available, it is not always given that CUDA should be used for CDPAM. One reason may be that there's not enough free memory on the GPU. Then it makes sense to run it on the CPU instead.

E.g. instead of

`cdpam.CDPAM()`

allow the user to do

`cdpam.CDPAM(device=my_device)`

**Comment by pranaymanocha** [comment]
Sorry for my delayed response. I uploaded a new version to pypi which tries to add the functionality that you mentioned. Please feel free to reopen this issue if there are more questions or suggestions.
