### ISSUE TITLE
Plans for a Pytorch model? 

### ISSUE THREAD

**Issue by mpariente** [pranaymanocha/PerceptualAudio#3]
Hi Pranay Manocha, 

This looks very nice !
Also, thanks a bunch for the data, that's very generous to share it. 

The obvious question is : do you plan on making a similar codebase for Pytorch or do you leave it to the community?

**Comment by pranaymanocha** [comment]
Hi.
Thanks for the nice words! :) Currently, there are no plans to make a pytorch codebase so I will probably have to leave it to the community for the time being. 

Thanks!

**Comment by shamoons** [comment]
Would love a PyTorch model somehow.... are there any other differentiable PyTorch based models that anyone knows of?
