### ISSUE TITLE
Is it possible to quantify on spectrograms instead of audios?

### ISSUE THREAD

**Issue by james20141606** [pranaymanocha/PerceptualAudio#7]
Hi, thank you for the codes, the paper on audio JND is very interesting! I just started running your codes and it seems that the model works on audios instead of spectrograms. Do you have the model which could take spectrograms as input?

**Comment by pranaymanocha** [comment]
Hi. Thanks for the comments. This repo currently does not have code (and trained model) that takes spectrograms as input. But there isn't much that needs to be done to make it compatible for spectrograms. The only change would be changing the dataloader (input) as well as the stride in conv2D for training. Currently, I am not planning to put a spectrogram trained model as the whole purpose of using waveform was to use the phase information that is useful for audio quality prediction, which the magnitude spectrogram doesn't use, but I'll be happy to debug out your code if you have any problems. Thanks!

**Comment by pranaymanocha** [comment]
Hi,
I'll close this issue for now, but please feel free to reopen it if you need any more clarifications!
